name: MorvenCosmetics
version: ${project.version}
main: me.cuft.MorvenCosmetics.Main
api-version: 1.16
commands:
  cosmetics:
    description: Cosmetic Chooser
  setcurrency:
    description: Sets the currency wanting to be used
